CREATE TABLE `employee` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `JOINING_DATE` datetime DEFAULT NULL,
  `SALARY` decimal(8,2) DEFAULT NULL,
  `SSN` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;